### ISSUE TITLE
Block List users appears in Allow List Email:

### ISSUE THREAD

**Issue by Taneyev** [bhadaway/stop-spammers#100]
I added "test" in my Block Lists

In the log Report, last column (Reason) I found: "Allow List Email:test"  but "test" is not in Allow Lists, it's in Block Lists! 

Why is not "Block List Email:test"   ? 

Thankyou in advance!

![Reason](https://user-images.githubusercontent.com/53412689/62014762-c636b780-b19c-11e9-8a2d-a23b6186d684.png)

**Comment by bhadaway** [comment]
Which exact block list is it in and can I see a screenshot of the full log (hiding anything that's sensitive)?

**Comment by Taneyev** [comment]
Thankyou for your answer, the log is not present now. I tried to replicate the scenario but now I obtain a different result: Deny List Email:test

I sent you a small donation, thankyou for mantaining this plugin!

antonio

**Comment by bhadaway** [comment]
Ah, probably just a cache thing then. Should be good now, but let me know if it happens again.

Thank you very much. Every dollar counts. The better I can keep food on the table and a roof over my head, the more time I'm able to contribute to projects like this. 💙
