### ISSUE TITLE
how to white list webhook from zappier?

### ISSUE THREAD

**Issue by nechamashor** [bhadaway/stop-spammers#103]
I use webhook with zappier and sometimes the plugin is blocking the information. how can I white list the webhook task that sends from zappier?

**Comment by bhadaway** [comment]
Actually, it looks like Zapier uses Amazon servers, so it might be as simple as checking the box for _Allow Amazon Cloud_ under _Allow Lists_.

I'll troubleshoot further if that doesn't do the trick.
