### ISSUE TITLE
Log Size / Location

### ISSUE THREAD

**Issue by stinson317** [bhadaway/stop-spammers#104]
The log size is very limiting.    I was trying to research an issue but the event time was before the last record in the log.    My questions  1) where is the log stored?  Possible to access outside the plugin?
2) possible to increase size (answer to 1 may answer 2).

**Comment by bhadaway** [comment]
1. The spam log data is stored in your database; there's no physical file, folder, or location for this log. Depending on your hosting environment, you most likely have several access logs of various types that might be useful to you. You probably already know that.

2. Yes, you can increase it under _Stop Spammers > Log Report_. Again, you probably already know that and are looking to log beyond just the last 100 entries.

There are a couple inelegant hacks that might by worthwhile to you:

1. Editing ss_reports.php, line 108, to add a larger value than 100. This will of course get overwritten when the plugin is updated. Altering this via your theme's functions.php file might be possible or better yet, via a custom plugin, could help you avoid that issue.

2. The easiest thing to try, which I haven't tested, but I think would work... just go to the log report page, right-click on the log size dropdown, inspect the code, and edit the value, changing it to say, 1000, and then update. Not pretty and might cause some slowness, but up to you if you want to try it.
