### ISSUE TITLE
Allow list letting in users from blocked list

### ISSUE THREAD

**Issue by pbeenz** [bhadaway/stop-spammers#106]
Hi there,
I can't reconcile the log-file with the configuration .
The Allow list looks like this: 
219.nn.86.nn
202.7.nn.nn
210.nnn.32.nnn
118.149.1nn.nn
118.148.2nn.nn
118.1nn.nnn.6
118.nnn.196.nnn
202.7.nn.nn
180.nnn.231.nn
these are all legitimate IP's and there are a number of legitimate email addresses as well that I've removed for privacy reasons. 

The block list looks like this:
admin
paul*
kimbra*
148.72.232.121
185.90.61.85
221.235.184.101
185.31.159.110
145.239.123.117
142.4.212.175
192.99.13.29
62.210.80.59   + many more IP's

However I get the following in the Log:

2019/09/11 12:21:44 | -- | 146.255.101.216 | kimbra-2 | /wp-login.php | Allow List Email:kimbra*:kimbra-2
-- | -- | -- | -- | -- | --
2019/09/11 12:21:39 | -- | 146.255.101.216 | paul-2 | /wp-login.php | Allow List Email:paul*:paul-2

I dont understand why kimbra-2 and paul-2 are allowed to attempt a login when the block list has kimbra* and paul* rules.

Any ideas would be appreciated, thanks Paul.

**Comment by bhadaway** [comment]
Try just:

paul
kimbra

Without the wildcard.

**Comment by pbeenz** [comment]
Hi Bryan thanks for the response, unfortunately the logon attempts are still occurring (even without the wildcard). I've downloaded your source files and will have look myself when I get some time. Great app by the way, thanks for writing it, cheers Paul.

**Comment by bhadaway** [comment]
Are they just attempts that you're seeing in the log, or are they actually successfully registering?

I actually didn't create this plugin. I was a long-time user and when it went down one day, I decided to adopt it to keep the project alive.

So, I do what I can, but definitely need all the help I can get. :)
