### ISSUE TITLE
Blocked IPs don't get blocked. Please tell me what I am doing wrong

### ISSUE THREAD

**Issue by dfumagalli** [bhadaway/stop-spammers#109]
Hello,

every day I recevie a large amount of Stop Spammers Site Lockout Notification emails.
They are like:

```
A lockdown event has occurred due to too many failed login attempts or invalid username: Username: Page IP Address: 89.35.39.60

IP Range: 89.35.39.*
```

The largest amount comes from 89.35.* and the user name changes all the time.

My blocks list is this:

```
188.240.0.0/16
188.213.0.0/16
89.35.0.0/16
85.204.0.0/16
104.248.195.0/24
```

Now, shouldn't the `89.35.0.0/16` line prevent the constant spam of the messages?

I even excluded the country related to that IP range (Romania) but no luck as well.
I checked allow list and that IP range is not included.

Best regards,
D.F.

**Comment by bhadaway** [comment]
Hmm, are you using any other anti-spam or security plugins? I'm not entirely sure this is  completely related to just Stop Spammers.

Also, are you using any sort of custom login plugin? It's possible that Stop Spammers isn't protecting it at all.

Try adding _89.35.*_ and _89.35/16_ to your block list.

**Comment by dfumagalli** [comment]
Hello,

I have some stuff that could conflict, but I am not sure.
Here's the list:
Akismet
Sidebar Login
Register Plus Redux

Not sure if the last 2 could cause issues. I had no fake users registrations or similar for a long time so I think Stop Spammers is doing its job with them.

**Comment by bhadaway** [comment]
Akismet is fine.

Sidebar Login is probably fine.

Register Plus Redux is most likely a conflict.

Looks like that plugin has been abandoned for a long while now:

https://wordpress.org/plugins/register-plus-redux/

I recommend replacing it with Theme My Login, but this version specifically:

https://downloads.wordpress.org/plugin/theme-my-login.6.4.17.zip
