### ISSUE TITLE
$this can not be used in static function.

### ISSUE THREAD

**Issue by nextgenthemes** [bhadaway/stop-spammers#111]
Found this kind of by accident.

https://github.com/bhadaway/stop-spammers/blob/de48b3c017690f523ea79e8c1a52b8ea84e5e468/modules/chkvalidip.php#L24-L25

**Comment by bhadaway** [comment]
Can I get some more information please? Thank you.

**Comment by nextgenthemes** [comment]
What more info to you need ???? I marked the exact lines. Its actually a method not function. You are not allowed to used `$this` in a static method.

**Comment by bhadaway** [comment]
I'm sorry if you're frustrated or are just having a bad day, but there's no call for being rude here.

I simply misunderstood and needed more context.

Okay, not allowed to use `$this`. Why? Is this according to the WP handbook, is this something that's been deprecated in PHP 7, is this simply a PHP no-no in general, with possible vulnerabilities?

Does it cause any actual errors or anything to break?

That's correct; I adopted this plugin. And I can use all the help I can get, so thank you very much for reporting this.

**Comment by nextgenthemes** [comment]
I am not into much OOP myself but at least I know what that means. How about you ask your favorite search engine about it instead of me? I really do not get it.

A `static` method is well **STATIC** so you can not use `$this` in a instance its absolute basic PHP OOP. I do know know if it causes issues, I just ran a code analyzer over my entire site directory and this popped up. I am to busy right now to look into this until someone wants to pay me for it because I am already coding to much shit that makes no money. I just wanted to report it and expected anything but this. Even completely ignore it would be a better response.

WP Handbook????? Again I think its probably fine to just remove the static keyword, I do not know if PHP actually acts as if the method is not static when you use `$this` in there but is wrong code and has nothing to do with WP. I can not tell you if it causes any issues or of the code functions correctly but I would expect from you to figure that out, at least make some basic effort to. Its basic PHP OOP. I never said this is a breaking issue or anything its just wrong code, and you probably should know some basic PHP of you take over a plugin like that. If you consider my this basic expectation rude then so be it.

And you are welcome.

**Comment by bhadaway** [comment]
Fixed and will be in the next update.
