### ISSUE TITLE
Plugin seems to have stopped working

### ISSUE THREAD

**Issue by PINKbyPuck** [bhadaway/stop-spammers#114]
Hi, I wanted to give you the heads up that there might be a plugin conflict that prohibits your plugin form functioning correctly. Because I keep getting new spam users. 
They come through with words on the block list and spam words list all in one user.

This is happening since yesterday.
It could be because of a plugin update, I updated 3 plugins:

Ninja Forms 3.4.21 to  3.4.22
Redirection 4.4.2 to  4.5.1
Yoast SEO Premium 12.5 to  12.5.1

Am checking by myself what I can do, but as for now my input did not result in fewer user spam.

Website is: [https://fsdc.nl/](https://fsdc.nl/)

**Comment by bhadaway** [comment]
1. Are user registrations going through Ninja Forms?

2. Is _Stop Spammers > Protection Options > Only Use the Plugin for Standard WordPress Forms_ checked?

**Comment by PINKbyPuck** [comment]
1. Hi, no they are completely avoiding that form, I think. As in, I cannot see any registrations from the NF forms, so I suspect they are not using those form.
2. Nope, that is not checked.

Somehow 2 days after this email the issue fixed itself. So I'm guessing it was a conflict somehow, or I did something to fix it without knowing. Thanks for the help anyway.

**Comment by bhadaway** [comment]
It happens like that sometimes. :)
