### ISSUE TITLE
error in ss_check_white.php (calling addons )

### ISSUE THREAD

**Issue by jetsam729** [bhadaway/stop-spammers#115]
ss_check_white.php: line 25
`$reason = be_load( $add );`

must be (min)
`$reason = be_load( $add, $ip );`
or (as in ss_check_post.php:23 for _compat_)
`$reason = be_load( $add, ss_get_ip(), $stats, $options, $post ); `

else get err:
**PHP Fatal error**:  Uncaught ArgumentCountError: **_Too few arguments_ to function be_load(), 1 passed**
***
(be_load defined as 
`function be_load( $file, $ip, &$stats = array(), &$options = array(), &$post = array()) `
 - (_must be  min 2 param in_) or define func prm($ip) as **$ip =** '', ?
- and strip comm **//** at stop-spammer-registrations-new.php:419
`// require_once($file[0]);`

**Comment by bhadaway** [comment]
Thank you!

Fixed, and will be in the next update.
