### ISSUE TITLE
Spam Folder

### ISSUE THREAD

**Issue by smihpix** [bhadaway/stop-spammers#140]
Forgive me if I'm here by mistake but does stop-spammers show you emails that it has deemed spam so I can check if something is spam that shouldnt be?

**Comment by bhadaway** [comment]
Hi smihpix,

Stop Spammers doesn't capture and store the actual content of attempted messages, it just checks them for bad behavior and then logs the event, username, IP, etc.

You can see those details under:

_Stop Spammers > Log Report_

**Comment by smihpix** [comment]
Will this log show if if deemed something was mistaken spam, I suspect like with other spam filters I should check to make sure it is not trapping
valid email?

Thank you,
Steve Smith

Photography & Video Production Services
www.smithproductions.net	

360-808-7322

**Comment by bhadaway** [comment]
You want to use the settings under _Stop Spammers > Challenge & Deny_ in order to handle that circumstance.
