### ISSUE TITLE
Allow request - Send mail to blocked (suggestion)

### ISSUE THREAD

**Issue by PaulRunner** [bhadaway/stop-spammers#142]
When allowing a customer from the allow request list, it would be great to have option to send email informing that he/she has access again. Best with different language features.
Kind regards
Paul.

**Comment by bhadaway** [comment]
Hi Paul,

It's definitely a good idea on paper, and has been suggested before, but I have concerns about sending emails from the server to random users/customers, which could still be spammers even if they've been cleared.

Without a user carefully setting up their server for higher quality emails (which is not something 90% of people would know how to do, even if they actually knew that it needed to be done — 99% won't), it could lead to you, your website, your email address, and your IP getting blacklisted and seen as spam, which in turn can hurt other aspects of your brand's reputation.

If I create a pro version of Stop Spammers, this might be better suited as an advanced feature in that context.

Thanks

**Comment by PaulRunner** [comment]
Hi Bryan, 

Sure, webmaster should be able to decide if spam or not. 
But presently after allowing, i always need to send separate mail to that person. 
For your information: Mostly, the spam i receive in allow request, are from customers willing to change their password. 

Kind regards, 
Paul. 


Van: "Bryan Hadaway" <notifications@github.com> 
Aan: "bhadaway/stop-spammers" <stop-spammers@noreply.github.com> 
Cc: "Paul Gins" <paul.gins@compugraphics.be>, "Author" <author@noreply.github.com> 
Verzonden: Vrijdag 3 januari 2020 19:15:03 
Onderwerp: Re: [bhadaway/stop-spammers] Allow request - Send mail to blocked (suggestion) (#142) 



Hi Paul, 

It's definitely a good idea on paper, and has been suggested before, but I have concerns about sending emails from the server to random users/customers, which could still be spammers even if they've been cleared. 

Without a user carefully setting up their server for higher quality emails (which is not something 90% of people would know how to do, even if they actually knew that it needed to be done — 99% won't), it could lead to you, your website, your email address, and your IP getting blacklisted and seen as spam, which in turn can hurt other aspects of your brand's reputation. 

If I create a pro version of Stop Spammers, this might be better suited as an advanced feature in that context. 

Thanks

**Comment by bhadaway** [comment]
You could also adjust this feature so that it gives them a second chance to prove that they're human rather than having to request it from you.

Then, you skip the email issue altogether.

**Comment by PaulRunner** [comment]
Hi Bryan, 

Adjust this feature, i went through all settings, is there kind of checkbox for it? 
Or i'll need to improve password reset form? 
FYI, i am using ultimate member plugin as well, including pwd reset form 

Kind regards 
Paul 



Van: "Bryan Hadaway" <notifications@github.com> 
Aan: "bhadaway/stop-spammers" <stop-spammers@noreply.github.com> 
Cc: "Paul Gins" <paul.gins@compugraphics.be>, "Author" <author@noreply.github.com> 
Verzonden: Vrijdag 3 januari 2020 19:58:25 
Onderwerp: Re: [bhadaway/stop-spammers] Allow request - Send mail to blocked (suggestion) (#142) 



You could also adjust this feature so that it gives them a second chance to prove that they're human rather than having to request it from you. 

Then, you skip the email issue altogether.

**Comment by bhadaway** [comment]
Under:

_Stop Spammers > Challenge & Deny_

are the settings responsible for sending you an email whenever someone has requested access, which you're then granting and manually emailing them that they're cleared.

Instead, you could change this entire workflow, by selecting one of the options from under **Second Chance CAPTCHA Challenge**.

**Comment by PaulRunner** [comment]
That was great and fast feedback Bryan! 
Thx a lot, kind regards 
Paul 



Van: "Bryan Hadaway" <notifications@github.com> 
Aan: "bhadaway/stop-spammers" <stop-spammers@noreply.github.com> 
Cc: "Paul Gins" <paul.gins@compugraphics.be>, "Author" <author@noreply.github.com> 
Verzonden: Vrijdag 3 januari 2020 22:02:41 
Onderwerp: Re: [bhadaway/stop-spammers] Allow request - Send mail to blocked (suggestion) (#142) 



Under: 

Stop Spammers > Challenge & Deny 

are the settings responsible for sending you an email whenever someone has requested access, which you're then granting and manually emailing them that they're cleared. 

Instead, you could change this entire workflow, by selecting one of the options from under Second Chance CAPTCHA Challenge .

**Comment by bhadaway** [comment]
You're welcome.
