### ISSUE TITLE
Error while login (apparently related to notify admin login setting)

### ISSUE THREAD

**Issue by legion1978** [bhadaway/stop-spammers#18]
The login is successful, but gives out this error and gets stuck in the login screen.

Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'ss_notify_admin' not found or invalid function name

**Comment by bhadaway** [comment]
Fixed and will be available in version 7.0.4, which I will push very soon.

**Comment by legion1978** [comment]
outstanding :)

**Comment by bhadaway** [comment]
:)
