### ISSUE TITLE
Jetpack protect and Profile Builder

### ISSUE THREAD

**Issue by siparker** [bhadaway/stop-spammers#19]
It says it has disabled itself because jetpack protect is enabled. Does jetpack protect offer the same level of protection and allow lists etc? If not ideally i would want SS to work alongside?

And second query will this work with the profile builder plugin from cozmoslabs

**Comment by bhadaway** [comment]
Generally, plugins that do the same thing, don't compliment each other. You don't get extra protection or power from doing that. Rather, they conflict with one another, break one or the other, or totally cancel each other out.

This is especially true of plugins that handle caching, SEO, and in this case, spam. It isn't automatically true that two plugins that have the same purpose will conflict, but that's sort of the golden rule: pick one and stick with it.

Of course, there are millions of variables and it isn't practical to test every possibility, but in this case, there happen to be known conflicts with Stop Spammers and Jetpack Protect.

I realize that Jetpack does a lot more that just this one feature, so it can be difficult to delete it, but if you do decide to stick with Stop Spammers, I can likely recommend other plugins as well to replace those Jetpack features you'll now be missing.

**Comment by siparker** [comment]
I absolutely want to stick with stop spammers. Jetpack just updated and added the protect thing in and activated it.

I have no idea if it manages the blacklists or any of the other features i use stop spammers for. and it certainly doesn't offer the same allow requests that are very important to me.

I was just wondering if their protect thing had some sort of specific purpose that was better than a certain part of stop spammers that might be worth using. but i think i will just disable jetpack as i dont use any of the other features of it anyway

**Comment by bhadaway** [comment]
Perfect. Easy peasy decision then. :)
