### ISSUE TITLE
Stop Spammers has disabled itself.

### ISSUE THREAD

**Issue by trovaseo** [bhadaway/stop-spammers#194]
Has anyone experienced this issue and know how to disable the Jetpack Protect feature?
Error message: "Jetpack Protect has been detected. Because of a conflict, Stop Spammers has disabled itself.
You do not need to disable Jetpack, just the Protect feature."

**Comment by bhadaway** [comment]
As I understand it, Protect is no longer in the main Jetpack plugin, but rather, there's now a Security addon for Jetpack. is that present?

**Comment by trovaseo** [comment]
Thank you for the response. I ran an update on the Jetpack plugin and then it automatically deactivated. Not sure what's happening. Going to investigate further with another tool to scan the website for spam.

**Comment by webguyio** [comment]
https://jetpack.com/blog/build-your-own-jetpack-now-with-individual-plugins/

What happened is Jetpack automatically installed and activated Jetpack Protect. You need to go to your Plugins page and deactivate and delete only Jetpack Protect and then you should be able to use Stop Spammers again.
