### ISSUE TITLE
compatibility with Akismet plugin

### ISSUE THREAD

**Issue by acceptjang** [bhadaway/stop-spammers#20]
Hi.
Recently I have been getting a unwanted new user registrations on my website.
Before I am trying to install ‘Stop Spammers’ plugin, I have some question.
‘Akismet’ plugin was installed and is using on my website.
I wonder that this plugin has compatibility with Stop Spammers plugin or not when installed. Is there any problem work together both ‘Akismet’ plugin and ‘Stop spammers’ plugin?
I need your kind opinion and advice.
Thank you so much in advance.

**Comment by bhadaway** [comment]
Yes. They're compatible. In fact, Akismet can integrate into Stop Spammers to improve its blocking capabilities.

However, Stop Spammers is very aggressive, much more so than Akismet. So, while it'll likely stop the spam you're dealing with, it'll also be a bit more advanced to manage, including the fact that legitimate users will now sometimes be blocked as well, which is something you'll now have to include into your workflow: clearing real users that get stuck in the spam filter.

There's always going to be some trade-off between security and convenience, and it completely depends on your preferences, which is more important in that balance.
