### ISSUE TITLE
system.multicall update needed

### ISSUE THREAD

**Issue by maledettobue** [bhadaway/stop-spammers#22]
Hi, 

could you update **system.multicall** addon to PHP7?

This is the report from "PHP compatibility checker" plugin:

FILE: /home/…/www/wp-content/plugins/multicheck/MultiCheck.php
————————————————————————————————————————————-
FOUND 4 ERRORS AFFECTING 4 LINES
————————————————————————————————————————————-
36 | ERROR | Global variable ‘$HTTP_RAW_POST_DATA’ is deprecated since PHP 5.6 and removed since PHP 7.0 – use php://input instead.
37 | ERROR | Global variable ‘$HTTP_RAW_POST_DATA’ is deprecated since PHP 5.6 and removed since PHP 7.0 – use php://input instead.
38 | ERROR | Global variable ‘$HTTP_RAW_POST_DATA’ is deprecated since PHP 5.6 and removed since PHP 7.0 – use php://input instead.
40 | ERROR | Global variable ‘$HTTP_RAW_POST_DATA’ is deprecated since PHP 5.6 and removed since PHP 7.0 – use php://input instead.
————————————————————————————————————————————-

Thanks!  :-)

**Comment by bhadaway** [comment]
I see. Actually, the add-ons for Stop Spammers are no longer apart of the official plugin and so will no longer receive updates and support. That said, if the plugin is useful to you, you might get community help here or elsewhere (perhaps https://stackoverflow.com/) for manually updating your own copy's code to be PHP 7 compliant.
