### ISSUE TITLE
Wordfence MFA Problems

### ISSUE THREAD

**Issue by ZacharyDuBois** [bhadaway/stop-spammers#24]
When using Wordfence to add TOTP capabilities to the login (currently only tested on multisite), Stop Spammers locks the user out as a bot after submitting the MFA code.

Screenshot shows the reason it locked me out:
<img width="1321" alt="screen shot 2017-07-06 at 22 25 05" src="https://user-images.githubusercontent.com/2458289/27940686-1dbee198-629a-11e7-886e-d5f6436400a5.png">

It looks like (since Wordfence is adding a secondary login page with a single field on it) that stop spammers is not seeing an username on a "login" form thus blocking it. Just needs a check if the username field is set - not a check to see if its a Wordfence page.

**Comment by bhadaway** [comment]
These plugins aren't meant to be used together. I understand that they both have useful features that the other does not cover, but there's too much overlap, and they'll likely continue to conflict in other ways that you haven't noticed yet, not to mention it might be too much overhead on your site's memory to be running them both.

I know it's probably not the answer you want to hear, but you'll probably need to choose one and delete the other.
