### ISSUE TITLE
Fatal error: Cannot redeclare ss_get_options()

### ISSUE THREAD

**Issue by BenTen** [bhadaway/stop-spammers#25]
Hello,

I can’t activate the plugin, I get this error:

> Fatal error: Cannot redeclare ss_get_options() (previously declared in xxxxxx/wp-content/plugins/wp-social-sharing/includes/plugin.php:9) in xxxxxx/wp-content/plugins/stop-spammer-registrations-plugin/stop-spammer-registrations-new.php on line 252

wp-social-sharing is https://wordpress.org/plugins/wp-social-sharing/

Best Regards

**Comment by bhadaway** [comment]
There's a conflict with the prefix because both plugins have the same initials "SS," Stop Spammers and Social Sharing.

I'll contact the other plugin developer and see if I can get it sorted.

Thanks

**Comment by bhadaway** [comment]
No response from the author of that plugin. They appear to be MIA, as they don't respond to other user requests either.

There are many plugins that offer the same features. I highly recommend:

https://wordpress.org/plugins/addthis/
