### ISSUE TITLE
Icon fix

### ISSUE THREAD

**Issue by NicYetAnother** [bhadaway/stop-spammers#26]
![21-07-2017 08-47-45](https://user-images.githubusercontent.com/30337606/28454327-c4c5a900-6df2-11e7-8b72-c7d66d0d77aa.jpg)

A tiny problem :) - Any chance to fix the icon size please?

(Its too big, its the only icon that takes two lines)

**Comment by bhadaway** [comment]
Looks like you're using some kind of custom admin plugin? What plugin?

**Comment by NicYetAnother** [comment]
Ozh's Admin Drop Down Menu

http://planetozh.com/blog/my-projects/wordpress-admin-menu-drop-down-css/

**Comment by bhadaway** [comment]
Fixed and it'll be included in the next update.
