### ISSUE TITLE
Log Reports Addon

### ISSUE THREAD

**Issue by NicYetAnother** [bhadaway/stop-spammers#27]
Hi,

Have you removed the 'log reports' add on?

By that I mean the addon that let you download an excel file listing all the events.

The integrated report only lists upto 100 events (although I can only get it to show about 35) - on my site that only covers the last hour or two, and I really miss the ability of having a log that covers several days.

Thanks :)

**Comment by bhadaway** [comment]
It hasn't been "removed" per se as it was never actually packaged with Stop Spammers by default. But yes, the link to those add-ons has been removed and the intention is to no longer support them.

My goal with Stop Spammers 7 is to consolidate for less mess and moving parts and refine just the core features.

**Comment by NicYetAnother** [comment]
No worries, just thought I'd ask :)
 Love the work you're doing.

**Comment by dsgolfside** [comment]
this is a very valuable tool i use ....i just what to make sure its still compatible with the latest version of your plugin ?  Log Report Plugin Addon

**Comment by bhadaway** [comment]
Sorry, but I don't know. Support and testing for add-ons is no longer provided. All focus is on the core plugin now. Thanks.
