### ISSUE TITLE
code jammed into header when your plugin is on

### ISSUE THREAD

**Issue by leofitz7** [bhadaway/stop-spammers#3]
Hello,
When I have your plugin turned on I now get the following line jammed into my header and displayed on web pages.
Missing kpg_ss_addtoallowlist /home/metamo19/public_html/newstest/wp-content/plugins/stop-spammer-registrations-plugin/modules/countries/kpg_ss_addtoallowlist.php

I've turned off and removed your plugin until a fix is suggested.
Thank you,

Lon Kaufmann
www.marketwisetrader.com

**Comment by bhadaway** [comment]
Sounds like you're on a dated version of the plugin. Please make sure you have the latest version (currently 7.0):

https://wordpress.org/plugins/stop-spammer-registrations-plugin/

You might have to manually download and install to make sure you're fully up-to-date.

Let me know if the problem persists after you've updated and I'll investigate.

**Comment by leofitz7** [comment]
I re-installed it a couple times (v7) and the code now doesn't appear!
Thanks, your plugin is  a great one, glad its now working again !!

**Comment by bhadaway** [comment]
You're welcome.
