### ISSUE TITLE
Disable captcha/arithmetic on password reset?

### ISSUE THREAD

**Issue by mrlowe** [bhadaway/stop-spammers#30]
I'm getting a response with a blank body after Stop Spammers intercepts my site's password reset request and the user solves the arithmetic problem and clicks "Press to continue". I've looked in the old support forum and haven't found anything helpful.

Is there a way to turn this feature off, or a known fix to the blank response?

**Comment by bhadaway** [comment]
This is happening to you, one specific person, or multiple people?

The "blank body" is just a white screen, no error message?

**Comment by mrlowe** [comment]
The "blank body" was an html response with an empty <body> tag, so yes, just a white screen with no error message.

It was happening to multiple users on a single site. I could reproduce it before, but I can't reproduce it now. Feel free to close this issue; if it happens again I'll reopen it.

**Comment by bhadaway** [comment]
Thanks
