### ISSUE TITLE
How can I whitelist GravityScan?

### ISSUE THREAD

**Issue by drbrucehoag** [bhadaway/stop-spammers#33]
The folks at GravityScan tell me that the Stop Spammers code tricks GravityScan into thinking that a website has vulnerabilities that it doesn't have: specifically, that certain files are visible to the public, when in fact they're not.

GravityScan has said that I need to whitelist them in the Stop Spammers plugin.

How do I do that?

**Comment by bhadaway** [comment]
See: https://www.gravityscan.com/help/scan-settings/whitelisting-gravityscan/

Then, you can whitelist under _Stop Spammers_ > _Allow Lists_.

**Comment by drbrucehoag** [comment]
I am not a programmer.

Where is "Allow Lists"?

**Comment by bhadaway** [comment]
When you log into the WordPress admin for your website, from the main menu on the left, navigate to:

_Stop Spammers_ > _Allow Lists_

In the first box you see there, you can paste in the IPs from:

https://www.gravityscan.com/help/scan-settings/whitelisting-gravityscan/

And then save.

Thanks

**Comment by drbrucehoag** [comment]
Many thanks.

Done and dusted. :-)

**Comment by bhadaway** [comment]
You're welcome. :)
