### ISSUE TITLE
Long posts marked as spam.

### ISSUE THREAD

**Issue by artmuns** [bhadaway/stop-spammers#34]
I have a few users who like to leave very long replies (400-500 words) to forum topics (bbPress). Many get flagged as spam. Any way to alleviate this?

Thanks for any help.

**Comment by bhadaway** [comment]
I wonder if it's really that it's a long reply in and of itself that's triggering the filter, or perhaps the fact that it's such a long reply, just increases the odds that a spammy word will appear. But, spammers do traditionally leave lengthy replies.

You've reviewed the replies, and they're legit, not spam?

Are they including links in the replies?

Are you also using Akismet?

It might move the needle too far in the wrong direction, but you might try checking the "Only Use the Plugin for Standard WordPress Forms" box under _Stop Spammers_ > _Protection Options_.

**Comment by artmuns** [comment]
Thanks for the reply Bryan.

Yes, I do review the replies and while there occasionally is some profanity that gets caught, most of the time there is nothing I can discern that would trip the spam filter. I have white listed their IP addresses but that doesn't seem to help. I have the links allowed set to 3 and that isn't the problem either.

I am using Akismet also. Could it be that my spam tools are too robust?

I had thought about about checking "Only Use the Plugin for Standard WordPress Forms" but thought it would just make things worse.

BTW this has only recently started to happen.

Thanks again for any help.

**Comment by bhadaway** [comment]
I know it's not ideal, but try checking the "Only Use the Plugin for Standard WordPress Forms" box and see how it goes for a few days.

If it solves the problem, but doesn't let other spam in or only allows a small, manageable amount of spam in, we're good.

If it opens the flood gates, we'll have to dig in and have a deeper look.

**Comment by artmuns** [comment]
Thanks Bryan, will give it a try.

**Comment by bhadaway** [comment]
You're welcome. I'll re-open if you still need help.
