### ISSUE TITLE
IP 127.0.0.1

### ISSUE THREAD

**Issue by jjw8089** [bhadaway/stop-spammers#36]
I keep getting Allow List Requests from users with the IP 127.0.0.1.

Does that make sense? 127.0.0.1 is localhost.

Should I approve this? Or are the settings wrong in my installation?

Apart from this, I love the plugin – great work!

**Comment by bhadaway** [comment]
Skim https://github.com/bhadaway/stop-spammers/wiki/FAQs real quick.

Are you using Cloudflare or any other service in which changes the DNS and therefore the way IP addresses are logged?

If not, can you list any plugins you're using that handle contact form, commenting, or registering features?

**Comment by jjw8089** [comment]
We're not using Cloudflare or similar services. We use DNS Made Easy, and we have a dedicated server at WP Engine.

We use Contact Form 7 and BBPress. Those are are the only 2 plugins that handle contact forms, registering etc.

**Comment by bhadaway** [comment]
I'm scratching my head on this one.

I suggest firing off a quick support email to both WP Engine and DNS Made Easy to see if they're familiar with what might be the cause. I suggest something like:

"_Hello,

For some reason, my account is logging all user IPs as 127.0.0.1.

Is there something that I need to do to restore normal IP logging?

Thank you._"

Also, it just occurred to me. WP Engine is managed hosting. They might be running your site through Cloudflare by default?

**Comment by jjw8089** [comment]
Hi, here's the response that I got from WP Engine.

"Yes, we do. There's a server-side page cache set up known as Varnish. On our platform, nginx manages the caching and then proxies forward to Apache which handles uncached requests.

Hopefully that helps clear up what the issue is and helps the developer figure out a solution. From our notes I don't see anything on this particular plugin, but if you or the developer has any other questions feel free to let us know!"

Could that be causing the issues?
