### ISSUE TITLE
Allowing "/proceed-to-check-out/?wc-ajax=update_order_review"

### ISSUE THREAD

**Issue by graffitimadrid** [bhadaway/stop-spammers#37]
Dear Stop-spammers team,

I recently installed your plugin in my website and it has stopped 88 attemps since that time. It's a great tool to avoid being spammed but at the same time it is blocking bookings from customers.

I recently received a booking which was never completed. The booking was considered as spam on the " /proceed-to-check-out/?wc-ajax=update_order_review" process. 

I have already unselected the option which says "Check for Many Hits in a Short Time" to see if that helps. On the meantime I have contacted personally the customer.

Looking forward hearing from you,

Regards,

**Comment by bhadaway** [comment]
From your main WP admin menu, navigate to:

_Stop Spammers_ > _Protection Options_ > _Check the Box for "Only Use the Plugin for Standard WordPress Forms"_ > _Save_

**Comment by graffitimadrid** [comment]
Thank you very much. I will check now if that helps fix the issue.
