### ISSUE TITLE
Will this plugin work with WPBruiser on a BuddyPress Site

### ISSUE THREAD

**Issue by n2rga** [bhadaway/stop-spammers#38]
I used to use this plugin when it was a different name and loved it.
Will this plugin work with WPBruiser on a BuddyPress Site. It's the current Wordpress Single site.
The feature I'm mostly interested in Since WPBruiser has a Buddypress Plugin that takes care of Spam. Is the Spammer Registrations if they are listed in Stop Forum Spam BYE!
Mitch

**Comment by bhadaway** [comment]
See: https://github.com/bhadaway/stop-spammers/wiki/FAQs

That said, I don't have specific knowledge to say for sure that WPBruiser and Stop Spammers would conflict with one another.
