### ISSUE TITLE
threat scan

### ISSUE THREAD

**Issue by alekdude** [bhadaway/stop-spammers#39]
Hi Bhadaway, 
Today I installed stop spammers plugin cause I had just to much spams that Akismet plugin didn't recognize as such. 
I run the "threat scan" and this massage appeared: 

Warning: mysqli_set_charset(): Error executing query in /webroot/a/l/alekdude001/embracelifemagazine.com/www/wp-includes/wp-db.php on line 823

Warning: Cannot modify header information - headers already sent by (output started at /webroot/a/l/alekdude001/embracelifemagazine.com/www/wp-includes/wp-db.php:823) in /webroot/a/l/alekdude001/embracelifemagazine.com/www/wp-includes/pluggable.php on line 1210

I don't know what it means, all I know is that i couldn't open the website in several occasions. As I'm writing is working, but I expect this massage to appear again. 

Please give some advice

**Comment by bhadaway** [comment]
Check your _wp-config.php_ file and make sure that `define('WP_DEBUG', false);` is indeed set to false.
