### ISSUE TITLE
Receiving spam emails after putting site to maintenance mode

### ISSUE THREAD

**Issue by joannesl** [bhadaway/stop-spammers#41]
I installed this plugin to a subdomain of my wp multisite network because I received a lot of spam mails. I then decided to put that subdomain into maintenance mode and then I started to receive notification from stop spammers with this message:
“Webmaster,

A request has been received from someone who has been
marked as a spammer by the Stop Spammers plugin.

You are being
notified because you have checked off the box on the settings page
indicating that you wanted this email.”.

I checked the settings of the plugin and it looks fine to me. What can I do to stop those emails?

**Comment by bhadaway** [comment]
1. You're receiving these emails because of a bug or because actual spammers are submitting the Allow List requests?

2. You've gone into _Stop Spammers_ > _Challenge & Deny_ and unchecked the box for "Allow Users to Add to the Allow Request List?"

**Comment by joannesl** [comment]
1. This option is checked :"Blocked users see the Allow request form:" for "Users can see the form to add themselves to the request list, but lots of spammers fill it out randomly. This hides the request form."

2. this option is checked : "Enable email request:" for "Blocked users can add their email addresses to the the Allow List request. This will also send you an email notification."

I think i just have to disable the the second one. but how can they add their email if the option one hides the form?

**Comment by bhadaway** [comment]
Sorry, that description is a little confusing. I'll have to fix that with the next update. Uncheck both of them or at the very least, uncheck the email checkbox and the problem should be solved.
