### ISSUE TITLE
Cloudflare Coverage

### ISSUE THREAD

**Issue by Maikuolan** [bhadaway/stop-spammers#42]
Hi,

You can close this issue as soon as you've seen it if you like. I'm just posting this to let you know that a user (not me) has sought support for this plugin via the Stop Forum Spam forums, and this seemed the most expedient way to let you know about it.

Discussion can be found __[here](http://www.stopforumspam.com/forum/viewtopic.php?id=8249)__.

Kind regards,
Caleb.

*PS, I also created this same message at the old WordPress support channel, prior to seeing your announcement about moving support over to GitHub. Sorry about that.*

**Comment by bhadaway** [comment]
Yes, Stop Spammers is heavily reliant on IP addresses. When using Cloudflare, IPs must be restored. This has nothing to do with Stop Spammers and needs to be done anyways or any/all plugins used, anti-spam, activity logging, etc. that rely on IPs will be pretty much useless.

https://support.cloudflare.com/hc/sections/200805497-Restoring-Visitor-IPs will only be helpful if the user has a website hosted on a service where they have more complete control, which usually excludes shared hosting.

Feel free to send the user to this issue or for them to post a new issue and I'll be happy to provide one-on-one support to see if I can't help them restore IPs.

Thanks
