### ISSUE TITLE
Plugin does not have settings page

### ISSUE THREAD

**Issue by mark2090** [bhadaway/stop-spammers#43]
Where is the settings page found? 

According to your plugin FAQ, it does not show in WordPress Admin area. There is no settings page anywhere. Not even a "settings" link on the plugin itself, all it says is "deactivate". 

Did you change something here?

**Comment by bhadaway** [comment]
As opposed to being a sub-menu item under Settings, Tools, or Plugins, Stop Spammers has a tab all its own in the main WP admin menu.
