### ISSUE TITLE
Log report to custom email address

### ISSUE THREAD

**Issue by PAYload1976** [bhadaway/stop-spammers#44]
I would like an option to send out an logreport every 24 hrs to an defined email address.
I manage multiple sites so it would help alot..

Hope this is possible :-)

Thanks for this great plugin

**Comment by bhadaway** [comment]
Likely the only email feature that will remain is to alert an admin when someone requests access. Beyond that, future versions will continue to be more lean, focusing on core functionality, and not adding new bells and whistles.
