### ISSUE TITLE
Captcha not showing

### ISSUE THREAD

**Issue by abcwebftl** [bhadaway/stop-spammers#45]
I put in the recaptcha keys and see the box on the Challenge and Deny page. The message then shows… If the reCAPTCHA form looks good, you need to enable the reCAPTCHA on the Challenge & Deny options page. (see left)

I see no other place to enable it? THe captcha is not showing on the page?

The page I need help with: https://www.deco-line.com/my-account/

**Comment by bhadaway** [comment]
I see. Yes, the CAPTCHA is meant to appear on the block page _if_ someone is caught in the filter. Not on the login/register pages. That would be managed by the theme or plugin responsible for your login/register form.

It looks like you're using WooCommerce to do so.

You might give this plugin a try:

https://wordpress.org/plugins/no-captcha-recaptcha-for-woocommerce/
