### ISSUE TITLE
Block List and Web Services entries wiping by themselves

### ISSUE THREAD

**Issue by floopydoopy** [bhadaway/stop-spammers#46]
I'm not sure why, but it seems that every so often on only one of my websites using Wordpress and Stop Spammers, the Block List and Blocked TLDs as well as any Web Services keys get wiped.

When I notice (like today) I have to copy them back in and save them. Then it's good for a few weeks to months and I'll notice it again.

I usually notice when someone on a blocked TLD like .ru is able to sign up.

I have no idea why this is only happening on one of my websites and not on the two others.

Have you seen this elsewhere? Any suggestions on how to troubleshoot it?

CentOS-based LAMP server, nothing special and all sites have more or less the same install of WordPress and plugins.

Thanks!

-ALlan

**Comment by bhadaway** [comment]
I haven't seen this issue before.

It sounds like you might need to repair your database.

Also, is everything fully up-to-date?

**Comment by floopydoopy** [comment]
Re: [bhadaway/stop-spammers] Block List and Web Services entries wiping by themselves (#46)


yes, it's the lastest version. I'll have to take a look at the DB and see if there's anything amiss.

It's been happening every so often for at least the past year. It only happens on this one site so I'm wondering why... I'll let you know what I find out.

Thanks!

Wednesday, February 7, 2018, 8:18:44 AM, you wrote:





I haven't seen this issue before.
It sounds like you might need to repair your database.
Also, is everything fully up-to-date?

**Comment by bhadaway** [comment]
Repairing a database in cPanel or WHM is pretty straightforward:

https://documentation.cpanel.net/display/70Docs/MySQL+Databases

Other than that, you might look at what plugins that one site has installed, that the other 2 do not, as therein might lie the conflict.
