### ISSUE TITLE
Wordfence

### ISSUE THREAD

**Issue by ibekimc** [bhadaway/stop-spammers#47]
Hi,

Do you have any experience using this with Wordfence? I'm looking to enhance our anti-spam efforts and this or cleantalk seem like the best options but I use Wordfence as my main line of defense so I don't want to compromise that.

Thanks!

**Comment by bhadaway** [comment]
Please see https://github.com/bhadaway/stop-spammers/wiki/FAQs, which I also just updated to provide clearer advice on the subject. Thanks.
