### ISSUE TITLE
Stop Spammers is blocking me

### ISSUE THREAD

**Issue by Cillacil** [bhadaway/stop-spammers#48]
Hi, I installed stopspammers on my WordPress site but every time I try to log in, it thinks I'm a spammer and makes me validate. Then it sends me an email notice that I'm a spammer try g to log in. How do I configure it so that this does nt happen to me every single time? Plus I hope this isn't happening for legit users. I don't want to scare them away. My site is https:// holmeselectrical.net.

**Comment by bhadaway** [comment]
Hi Cillacil,

Please see the first FAQ listed on: https://github.com/bhadaway/stop-spammers/wiki/FAQs.

If that doesn't help, let me know and I'll re-open this issue.

Thanks
