### ISSUE TITLE
Does not block Spam Words List in Cyrillic

### ISSUE THREAD

**Issue by mrdenisters** [bhadaway/stop-spammers#49]
I have a real estate site and bots add ads, despite the fact that the page is protect a recaptcha and stop spam filters are enabled. [https://prnt.sc/iqm9xg](url)
Spam word: лайки is in the title and text of the ads. 
Spam Header Example: Мы платим за лайки! &#8212; Выплаты по требованию!

How to add support for Cyrillic Spam World?

**Comment by bhadaway** [comment]
Right now, Stop Spammers only supports English. Overall, this is something that needs to be addressed with supporting other languages:

https://github.com/bhadaway/stop-spammers/issues/14

Without help from others, this is not likely to be something that I'll make much progress on.
