### ISSUE TITLE
try to understand the cache message

### ISSUE THREAD

**Issue by holipin** [bhadaway/stop-spammers#51]
Stop Spammers  > Log Report > table section >  Reason Header column

What does Failed Registration: Bad Cache mean ? Also i see log mention goodcache later , what does good cache mean ?

**Comment by bhadaway** [comment]
This simply means that an attempt either succeeded or failed based on a previous success or failure.

If a success or failure is happening that shouldn't, you can always whitelist or blacklist specific details about that user or simply clear the good or bad caches.
