### ISSUE TITLE
Stop Notification Emails

### ISSUE THREAD

**Issue by OverloadUK** [bhadaway/stop-spammers#53]
How do we turn off 'Allow List...' email notifications?

E.g. A request has been received from someone who has been
marked as a spammer by the Stop Spammers plugin.

You are being
notified because you have checked off the box on the settings page
indicating that you wanted this email.

**Comment by bhadaway** [comment]
Go to _Stop Spammers > Challenge & Deny > Uncheck the box for "Notify Webmaster When a User Requests to be Added to the Allow List" > Save_
