### ISSUE TITLE
Is it possible to whitelist all customers?

### ISSUE THREAD

**Issue by SSSV** [bhadaway/stop-spammers#56]
A legit customer who purchased from our site (running WooCommerce) was blocked from leaving a review. Is it possible to automatically whitelist anyone who has purchased from us? Thanks!

**Comment by bhadaway** [comment]
You'll want to use the solution listed here concerning WooCommerce:

https://github.com/bhadaway/stop-spammers/wiki/FAQs

Thanks

**Comment by SSSV** [comment]
This option was already checked when the customer's review was blocked.

**Comment by bhadaway** [comment]
Then other than fine-tuning your settings and manually dealing with people that get blocked when it occurs, I can't really think of anything out-of-the-box to do anything that specific.

Of course, anything is possible in terms of customizing, but that would be beyond the scope of what I could help with.

Off the top of my head though, if your site is mostly membership-based, you could add conditionals to certain checks like https://developer.wordpress.org/reference/functions/is_user_logged_in/.

If customers don't have to be logged in to leave reviews though, then there's no practical way I can think of to differentiate them from other traffic, beyond tracking all their IPs, which is unreliable and brings you straight back to using the plugin's default whitelist anyway, which you would like to avoid.

My gut is telling me this is probably a creative problem-solving issue, but I'm coming up empty at the moment.
