### ISSUE TITLE
stop spammers error on upgrade

### ISSUE THREAD

**Issue by thatmtnman** [bhadaway/stop-spammers#57]
Hello Brian,

The following error occurs. Particularly bad since it exposes the username for the website:

WordPress database error: [You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE active = 0 AND user_login = 'admin' ORDER BY signup_id DESC LIMIT 0, 1' at line 1]
SELECT * FROM WHERE active = 0 AND user_login = 'admin' ORDER BY signup_id DESC LIMIT 0, 1

Warning: Cannot modify header information - headers already sent by (output started at /home/USERNAME/public_html/wp-includes/wp-db.php:1399) in /home/USERNAME/public_html/wp-login.php on line 422

Warning: Cannot modify header information - headers already sent by (output started at /home/USERNAME/public_html/wp-includes/wp-db.php:1399) in /home/USERNAME/public_html/wp-login.php on line 435

Error occurred after adding 'admin' to banned names list, (no user 'admin, btw), and then attempting a registration. Even after removing the word 'admin' from the block list, the error persisted. 

I've had to turn your plugin off. 

Thought you should be aware.

cheers!

**Comment by bhadaway** [comment]
Hi thatmtnman,

Thanks for the report.

However, please note that these are only warnings. Also note, anytime a PHP issue exists, regardless of Stop Spammers, that your username will be exposed in the displayed info.

The solution to all issues here is to disable errors from displaying on the front-end, which is a good idea on a production site anyway. Check your wp-config.php file and make sure that `WP_DEBUG` is set to `false`.

Thanks

**Comment by thatmtnman** [comment]
Hey Bryan!

Thank you so much for the reply!  I had the flag set to false, but I guess
it got reset when the upgrade happened. Everything seems to be working as
it should.

Very sorry to trouble you!

cheers!

Frank



<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by bhadaway** [comment]
No worries. When in doubt, it's always best to double-check.
