### ISSUE TITLE
typo on web services screen in WP plugin?

### ISSUE THREAD

**Issue by pjbarry21** [bhadaway/stop-spammers#59]
The link itself goes to the .org address, but if someone is just copying the visible link or typing it in... I'd used projecthoneypot.org in the past, so I was familiar with it and seeing the .com made me pause for a sec.

BTW -- great plugin. First time in months a site I've been working on had a full day with no spam registrations getting recorded. Thanks!

![image](https://user-images.githubusercontent.com/6089948/40782436-49189d14-64ad-11e8-8989-3c3d78acc7c0.png)

**Comment by bhadaway** [comment]
Fixed. You'll see it in the 7.1 update. Thanks.
