### ISSUE TITLE
Error when reporting Spam to Stop Forum Spam

### ISSUE THREAD

**Issue by TheGeekGoddess** [bhadaway/stop-spammers#6]
When submitting to SFS you get a modal that gives the response "data submitted successfully" (surrounded by <p> tags that are visible for some reason), but the inline response says there was an error reporting it, yet still has the same response listed "data submitted successfully". See attached screen shot.

Note: the information IS being submitted successfully. I checked SFS after submission and the report is there.
![screen shot 2017-05-21 at 12 09 32 pm](https://cloud.githubusercontent.com/assets/7432845/26285548/1b6edbe4-3e20-11e7-824c-dec1ff1bcac0.png)

**Comment by bhadaway** [comment]
That is confusing. Let me check on this...

**Comment by Truck3rCl0ck** [comment]
I have the same issue. I tried getting a different API key for giggles and no luck.

**Comment by bhadaway** [comment]
I'll test this out soon. Thanks.

**Comment by bhadaway** [comment]
This should now be sorted in version 7.0.3. Let me know if you're still experiencing confusing report messages and I'll re-open.

**Comment by TheGeekGoddess** [comment]
Can we reopen this? Now it is saying "Returning from Ajax" and is still showing an error.

**Comment by bhadaway** [comment]
Re-opened. And just to verify real quick, the report is actually being submitted still, it's just that the error message is given incorrectly?

**Comment by TheGeekGoddess** [comment]
No, this time the report wasn't being submitted. :(

**Comment by bhadaway** [comment]
Fixed and improved!
