### ISSUE TITLE
Spammers Getting Through

### ISSUE THREAD

**Issue by billdf99** [bhadaway/stop-spammers#61]
Hello, I hope I'm reaching out at the correct place. I updated the Stop Spammers plugin on a website I run (www.eastonchurch.org) last night (6/25/18). Since then, I've had three spam registrations on the site. I hope you can help resolve this issue. Thank you.

**Comment by bhadaway** [comment]
Hey Bill,

How long had it been since you updated? Were you updating from version 6?

Thanks

**Comment by billdf99** [comment]
Hi Bryan,

Thanks for the response.

I am sorry to admit this, but I've kind of been on autopilot with this plugin, since it worked so well. I basically just update it when a new version comes out. So I don't remember what version I had before updating, and I don't remember how long its been between updates. The version was likely whatever the previous public version was available, and the timeframe is whenever a new update comes out.

Sorry I can't give more details. Hopefully that helps a little.

**Comment by bhadaway** [comment]
I suspect that your settings (including all the IPs you'd previously blocked) were wiped when you updated, though they should still be saved in your database.

Try rolling back to version 7.0.9 (with the help of this plugin: https://wordpress.org/plugins/wp-rollback/) and then update to the latest version of Stop Spammers again.

No-go? You'll want to go over all your Stop Spammer settings and adjust/tighten them again (might be a good idea to check them anyway).

I haven't seen enough reports of this nor are there any issues on any of the sites that I run Stop Spammers on, so I'm not quite sure anything has changed to make the plugin less effective. Of course, I could be wrong. However, we'll see if more people report issues.
