### ISSUE TITLE
Plugin seems to of stopped working

### ISSUE THREAD

**Issue by SMVMARK** [bhadaway/stop-spammers#62]
I installed your plugin as I was having a lot of spam signups. This plugin seemed to work until recently where I am getting more spam signups than ever before.

It’s clear in my user list who is spam as the user role is ‘none’ where other real signups say ‘subscriber’ so is there a way of fixing or setting up this plugin so that if a role is not selected then these signups are automatically banned?

Looking forward to your assistance on this.

The website is www.supplymyvenue.com

Thanks
Mark

**Comment by bhadaway** [comment]
I suspect that your settings (including all the IPs you'd previously blocked) were wiped when you updated, though they should still be saved in your database.

Try rolling back to version 7.0.9 (with the help of this plugin: https://wordpress.org/plugins/wp-rollback/) and then update to the latest version of Stop Spammers again.

No-go? You'll want to go over all your Stop Spammer settings and adjust/tighten them again (might be a good idea to check them anyway).

I haven't seen enough reports of this nor are there any issues on any of the sites that I run Stop Spammers on, so I'm not quite sure anything has changed to make the plugin less effective. Of course, I could be wrong. However, we'll see if more people report issues.
