### ISSUE TITLE
resetting password is not working 

### ISSUE THREAD

**Issue by daron4ever** [bhadaway/stop-spammers#63]
Hi,
I always have incorrect password error with stop-spammers plugin when I try to submit new password.
I use Formidable Forms Registration plugin.
Do I need to change some options?
Thanks.

**Comment by bhadaway** [comment]
Hi Daron,

This may both resolve the issue and weaken the plugin at the same time, but it's probably the best option:

_Stop Spammers > Protection Options > Only Use the Plugin for Standard WordPress Forms_

Check this box and save.

Thanks

**Comment by daron4ever** [comment]
It works like a charm. Thanks!

**Comment by bhadaway** [comment]
You're welcome. :)
