### ISSUE TITLE
Spam Buddypress Registrations

### ISSUE THREAD

**Issue by CVTBrian** [bhadaway/stop-spammers#65]
I installed Stop Spammers last week to cut down on spam registrations on my BuddyPress site, but the plugin is allowing obvious spammers to fill out and submit the registration form.  I checked the Stop Spammers log report, and it shows fake email addresses ending in '.ru', '.pw', and '.xyz' as "Passed Registration:Good".  What do I need to do to prevent these spammers from registering?

**Comment by CVTBrian** [comment]
Thanks.  I had a few of those TLDs in my blocked list including .ru, but am still getting spam registrations with .ru email addresses.  I will try adding the others.

**Comment by CVTBrian** [comment]
I added the above TLDs last night.  So far this morning I had two registrations using .ru email addresses.

**Comment by bhadaway** [comment]
Under:

_Stop Spammers > Protection Options > Only Use the Plugin for Standard WordPress Forms_

Is that box unchecked?

**Comment by CVTBrian** [comment]
It is checked because we have a WooCommerce store.

**Comment by bhadaway** [comment]
I see. That's why they're getting by. You might consider also adding this security plugin:

https://wordpress.org/plugins/wordfence/

There are of course many other ways to harden WordPress if you look around.
