### ISSUE TITLE
Buddypress prop clogging debug reports

### ISSUE THREAD

**Issue by ethansmith** [bhadaway/stop-spammers#66]
The following notice is getting logged in the plugin's debug report repeatedly (during heavy site usage, several times a second). This isn't really causing me any distinct issues, and may be due to something weird on my end, but I thought you might like to know. Note that I've replaced potentially sensitive info with "XXX".
Cheers!
Ethan

Time: XXX
Error Number: 8
Error Type: Run-time notices. Indicate that the script encountered something that could indicate an error, but could also happen in the normal course of running a script. 
Error Msg: Undefined property: BP_Members_Component::$table_name_signups
IP Address: XXX
File Name: XXX/wp-content/plugins/buddypress/bp-members/classes/class-bp-signup.php
Line Number: 169
Memory Used, Peak: 68681728, 68681728

**Comment by bhadaway** [comment]
What version of Stop Spammers are you on?

**Comment by ethansmith** [comment]
Hah! I forgot to include the basics, eh?

v7.1 of your plugin. WP 4.9.7, BP 3.1.0

**Comment by bhadaway** [comment]
I know that Stop Spammers works fine with bbPress, and I know that some users are using it with BuddyPress as well.

Beyond the debug report, is anything actually getting tripped up? Are legitimate users unable to register or log in?

**Comment by ethansmith** [comment]
It's been working fine and nothing has been getting tripped up, although I imagine the process of flagging the error in the plugin's debug file every few seconds is taking a small toll on overall performance.

**Comment by bhadaway** [comment]
Okay, thanks for the note. I'm not sure of anything I can improve here at the moment, so I'll go ahead and close this issue for now.
