### ISSUE TITLE
Block doesn't work

### ISSUE THREAD

**Issue by RAndaro** [bhadaway/stop-spammers#68]
Hi!

I'm having issues with fake/spam users registering at my website. I am using your plugin and reCAPTCHA, I have included the emails in Block List and Blocked TLDs with and without wild cards (and made sure I check the To block usernames in this list, check this box-box), blocked all countries and signed up for all Web services, but I still receive fake's from the blocked emails e.g. *.instambox.com.
It is also strange, perhaps a clue, that all users, fakes as well as my own admin accounts, show my domain (not-dedicated) IP-address as User IP. 
Any idea why the block doesn't seem to bite? Could it have something to do with the IP-address being the same as for my server? I have used the default to whitelist admin IP.. Is there a safe way to not use this function or other alternatives (e.g. getting a dedicated IP) if this truly is their entryway?
Anyone else had this issue?

Any tips would be very appreciated!
Best,
Robin

**Comment by bhadaway** [comment]
Stop Spammers relies heavily on IP addresses, so I wonder if you're using Cloudflare or something else that disrupts the accurate logging of IPs and you need to restore visitor IPs?:

https://support.cloudflare.com/hc/sections/200805497-Restoring-Visitor-IPs

Also, is:

_Stop Spammers > Protection Options > Only Use the Plugin for Standard WordPress Forms_

unchecked?

**Comment by RAndaro** [comment]
Hi - thanks for your reply!

I have not installed anything like cloudflare as far as I know. I am using Bluehost as server and according to them they are not using anything like this and don't have any ideas for me.

I can further confirm Stop Spammers > Protection Options > Only Use the Plugin for Standard WordPress Forms is unchecked.

**Comment by RAndaro** [comment]
I believe it is the woocommerce registration for as it disappears if I deselect the reg form settings inside the wocommerce plugin.

I have noticed however that I receive admin-notification emails as these spammers register. This is interesting because I do not receive these emails when I add new users through my site's front-end, only if I add users in the back-end. 
So it seems to me somehow they are adding users not from the front-end, but as admins from the back-end? This might also explain why reCAPTCHA and any IP or email ban doesn't seem to bite. 
I have searched my site for malware and it is clean, and I have reset the password for all administrator accounts as well. 
What are your thoughts on this? Any ideas how this might be possible/how to stop it?

I thank you for your insights.
Robin

**Comment by RAndaro** [comment]
Hi,

I just wanted to share that my problem has been solved, and what solved it.

Apparently, I didn't have reCAPTCHA activated on the original wordpress registration form, only the reg. form I display on the front end.

When I activated it there the spamming more or less ceased! 

Thanks for your support.
Best
Robin

**Comment by bhadaway** [comment]
Thanks for the update.
