### ISSUE TITLE
Block e-mails with wildcard (i dont want them to register at my wordpress)

### ISSUE THREAD

**Issue by ku3hn** [bhadaway/stop-spammers#70]
Hi @ All, i love this tool but i cant block emails with a wildcard from "*@laysporji.info" how can this be?
Thx alot for your help, and sorry for the beginner question. :)
Daniel

![knpofclkoeghjpai-2](https://user-images.githubusercontent.com/43029531/45144482-8e0e3b00-b1be-11e8-9105-10c895f47b60.png)

**Comment by bhadaway** [comment]
Simply adding **laysporji** to the Spam Word List should work.

If that doesn't work, a more heavy-handed, but still fairly safe (in my opinion) option would be to add **.info** to the Blocked TLDs list.
