### ISSUE TITLE
Admin email and allow list request

### ISSUE THREAD

**Issue by rebeccacarney** [bhadaway/stop-spammers#73]
Hi there, 
I just have two questions about using this plugin. 
Firstly, is there a way to designate a different admin for notifications besides the one used in the general WordPress settings? 
Also, we received a notification with the following but I'm not sure how this user tried to access our website or if further action needs to be taken. 
> Webmaster,
> A request has been received from someone who has been marked as a spammer by the Stop Spammers plugin.
> You are being notified because you have checked off the box on the settings page indicating that you wanted this email.
> The information from the request is:
> Time: 2018/09/26 21:06:07
> User IP: 176.36.21.189
> User Email: burulov19803@gmail.com
> Spam Reason: 
> User Message: 
> Please be aware that the user has been recognized as a potential spammer.
> Some spam bots fill out the request form with a fake explanation.
> — Stop Spammers

Thank you!

**Comment by bhadaway** [comment]
Hi Rebecca,

1. Yes. Navigate to:

_Stop Spammers > Challenge & Deny > Notify Webmaster When a User Requests to be Added to the Allow List_

Here, you can set any email you like.

2. The **User Message** is the best way to decide how to respond to the request:

- If it's blank, just delete the request
- If it contains any links or gibberish per the usual spam message, thumbs down
- If it contains a relevant message from a real human trying to register, log in, or make a purchase, give them the thumbs up

Thanks
