### ISSUE TITLE
Ask : Label SPAM on Automated Email from New Post

### ISSUE THREAD

**Issue by Katigakutop** [bhadaway/stop-spammers#74]
Hi Stop Spammers Team

I set automatic email as notification for subscribers to a new post. But, recently i found that mail was labeled "Spam". This was never happened before i install stop spammers. 

Do you think it is linked to installation of stop spammers? If yes, would you like to help us to allow automatic mail without "spam" label?

Thank you

**Comment by bhadaway** [comment]
The only emails that Stop Spammers has anything to do with are the ones sent by the plugin itself, if you've set it to send you an email alert whenever someone who has been blocked requests access.

Outside of that, no, it doesn't do anything connected with the way your server handles mail.

Recommendations (in this order — trying each next step if the previous step doesn't resolve the issue):

1. Test your emails in all the different ways in which email might be sent from WordPress, your site, and server here: https://www.mail-tester.com/, and apply improvements based in its recommendations.

2. Install and configure this plugin: https://wordpress.org/plugins/postman-smtp/.

3. Sign up for G Suite to host your email: https://gsuite.google.com/. For only $5/month, of all the paid options to improve your email performance (if it gets to that point), it's definitely the cheapest and easiest.
