### ISSUE TITLE
Datas whipped out in User IP column (Dashboard->Users->All Users)

### ISSUE THREAD

**Issue by scriptorium11** [bhadaway/stop-spammers#76]
Hi,
This morning I've noticed that the User IP column (Dashboard->Users->All Users) was empty, which means that I am not anymore able to get any former or new users registration IPs and moreover to check these IPs against StopSpamForum, HoneyPot or BotScout, all services which are mostly useful to detect spammers.
I have to say that recently I had to install a new plugin to enforce the registration process: "User Verification" (a double time check registration process). Since then both the plugins were working fine together.
If you had any idea to help, I'd be glad to accept it.
Best
Gilles
Post Scriptum: I already rolled back to 7.09 version and upgraded again to 7.1, with no result

**Comment by bhadaway** [comment]
> Post Scriptum: I already rolled back to 7.09 version and upgraded again to 7.1, with no result

So, does that mean that you were on an old version and only updated recently, or have you been keeping the plugin up-to-date all along?
