### ISSUE TITLE
Buddypress Block IPs, URLs seemingly ignored

### ISSUE THREAD

**Issue by asdimoro** [bhadaway/stop-spammers#77]
I have used this plugin years ago for a Buddypress based website and found it beneficial. However, as i am utilizing this plugin for my Buddypress website (new), i have compiled a huge list of IPs from spammers, as well as domains such as 'maikl.ru' that I have listed to be blocked. This plugin seems to ignore most of these requests, and is instead flagging actual registrants as opposed to the spammers i have specified. Any help on this would be appreciated. mal.ru emails are relentless in registration spam

**Comment by bhadaway** [comment]
You might try blocking at the TLD level (_Block Lists > Blocked TLDs_).

Unless your website is massive, you're probably safe to block all of these:

```
.gq
.nl
.pl
.pw
.ru
.tk
.xyz
.xxx
```

I've never seen anything legitimate come through from these domains.
