### ISSUE TITLE
Stop spammers blocks Yandex browser

### ISSUE THREAD

**Issue by Eterion-com** [bhadaway/stop-spammers#78]
Stop spammers blocks Yandex browser (https://en.wikipedia.org/wiki/Yandex_Browser) users and Yandex services like Yandex Money.
![screen-2018120601](https://user-images.githubusercontent.com/24571435/49586762-1ee9e380-f973-11e8-9631-e493f04a3999.png)
![screen-2018120602](https://user-images.githubusercontent.com/24571435/49586778-27dab500-f973-11e8-8089-2a9a7eee994b.png)

**Comment by bhadaway** [comment]
Yes, Yandex is very commonly associated with spamming.

You can remove it from the block list if it's causing any issues for your site.
