### ISSUE TITLE
Question: Still supported and WordPress compatible?

### ISSUE THREAD

**Issue by oldrup** [bhadaway/stop-spammers#79]
Hi, and thank you for a nice plugin, keeping me and my visitors sane, as they don't have to fiddle with annoying captchas.

How well does Stop Spammers work with the latest WordPress 5.0?

Best regards
Bjarne

**Comment by bhadaway** [comment]
I'm using both together now, and so far, so good.

Stop Spammers doesn't really mess with anything that's been changed in 5.0.

Of course, you never know. Everything seems fine now though.
