### ISSUE TITLE
Use of undefined constant ss_user_reg_filter

### ISSUE THREAD

**Issue by micklevin** [bhadaway/stop-spammers#85]
Hi, I see occasional errors like one below:

xxx FastCGI sent in stderr: “PHP message: PHP Warning: **Use of undefined constant ss_user_reg_filter – assumed ‘ss_user_reg_filter’** (this will throw an Error in a future version of PHP) in **/var/www/html/xxx.ca/html/plugins/stop-spammer-registrations-plugin/stop-spammer-registrations-new.php on line 660**” while reading response header from upstream xxx

I hope you know how to fix that.

Thank you.

**Comment by bhadaway** [comment]
I'll try and take a look soon. Thanks for the heads up.

**Comment by artmuns** [comment]
Having the same problem and blocking valid IP addresses on Allowed List. Sends valid comment to Moderation. 

Time: 2019/04/11 22:59:20
Error Number: 2
Error Type: Run-time warnings (non-fatal errors). Execution of the script is not halted. 
Error Msg: Use of undefined constant ss_user_reg_filter - assumed 'ss_user_reg_filter' (this will throw an Error in a future version of PHP)
IP Address: 68.x.xxx.161
File Name: /nas/content/live/muxxxl/wp-content/plugins/stop-spammer-registrations-plugin/stop-spammer-registrations-new.php
Line Number: 660
Memory Used, Peak: 20971520, 20971520

**Comment by bhadaway** [comment]
Fixed.
