### ISSUE TITLE
All user with same IP 127.0.0.2

### ISSUE THREAD

**Issue by karnhack** [bhadaway/stop-spammers#86]
Hi,
I think I have a problem because all users appear with the same ip 127.0.0.2.
I not using Cloudflare or similar services. My active plugin list:

Akismet Anti-Spam
Contact Form 7
Cookie Notice
Shareaholic
Fourteen Colors
Mailchimp for WordPress
PDF Embedder
Postepay Gateway per Woocommerce
Really Simple SSL
Smush
WooCommerce
WooCommerce Menu Cart
YITH WooCommerce Ajax Product Filter
Yoast SEO

I have attached the phpinfo file in the link below. Thanks for the support

https://we.tl/t-zcGwNfYR6r

**Comment by bhadaway** [comment]
127.0.0.2 is the localhost. Your website is actually live, correct, not just testing on your desktop for example?

What hosting are you using?

Are you able to share the URL?

**Comment by karnhack** [comment]
No, the website does not run locally but on a hosting basis. The hosting is tophost.it
This is the website https://goo.gl/pqFm3L

Thanks for your help

Gianluca

**Comment by bhadaway** [comment]
Can you send an email to info@seeweb.it and ask them if there's any reason you wouldn't be able to record visitor IPs accurately?

**Comment by karnhack** [comment]
I contacted the hosting and they replied like this:
### Using HTTPS support, the CMS visits logging system, will always give with visitor IP: 127.0.0.2.
This unfortunately happens due to a system BUG. For the moment, the only solution is to insert the following statement at the beginning of the PHP input file (eg index.php or the configuration file): ###
`_SERVER['REMOTE_ADDR'] = $_SERVER['HTTP_X_FORWARDED_FOR'];` 

The plugin works well but could you help me understand how to insert this code?

**Comment by karnhack** [comment]
I entered the code in /index.php and now I see the IPs. Thanks for your help

`<?php
$_SERVER['REMOTE_ADDR'] = $_SERVER['HTTP_X_FORWARDED_FOR'];
/**
 * Front to the WordPress application. This file doesn't do anything, but loads
 * wp-blog-header.php which does and tells WordPress to load the theme.
 *
 * @package WordPress
 */

/**
 * Tells WordPress to load the WordPress theme and output it.
 *
 * @var bool
 */
define( 'WP_USE_THEMES', true );

/** Loads the WordPress Environment and Template */
require( dirname( __FILE__ ) . '/wp-blog-header.php' );`

**Comment by bhadaway** [comment]
Good to hear.

**Comment by karnhack** [comment]
It is normal that the list "allow list" is automatically written? I keep getting registrations and the ip 127.0.0.2 has been added automatically

**Comment by bhadaway** [comment]
Yes, this is normal. There could also be some residual stuff going, but as long as you're now able to accurately record visitor IPs, you should be good.

You may want to clear the logs and caches and generally go through all the settings of Stop Spammers and tighten things up.
