### ISSUE TITLE
Allow list values

### ISSUE THREAD

**Issue by maslanit** [bhadaway/stop-spammers#87]
I have a number of IPs in my allow list that I haven't entered. I'm not sure if they are there by default or based on some checked boxes in the options below or if they are being put their maliciously.  Any info on whether the plugin does anything to manage the allow list that would leave all these IPs there?

**Comment by bhadaway** [comment]
IPs can be added here in a number of ways that don't include you manually adding them:

1. Approving requests for access
2. Successful logins by admins

Do you log in from multiple locations, have other team members that use the website, or have an active community? If so, unless you have a specific reason to be alarmed, or any of those IPs come up on spam lists, everything sounds good to me.
