### ISSUE TITLE
Exclude reset password

### ISSUE THREAD

**Issue by victor-theoption** [bhadaway/stop-spammers#88]
Hi, I have some problems with the compatibility with a custom reset password because it blocks the "reset-password" url and all the search params that came from the email to reset the password.
The plugin works perfect it block all the user created spam, but i need not to block this url.
There's any solution, I tried by IP, but every user has another IP, it's an e-commerce.

Thank's in advance.

**Comment by bhadaway** [comment]
What's the other plugin you're using?

The surefire way to fix this, but that might leave you too vulnerable to spam, is:

_Stop Spammers > Protection Options > Only Use the Plugin for Standard WordPress Forms_

Check this box and save.

**Comment by victor-theoption** [comment]
@bhadaway it work like a charm.
I will check these days if no more spam user register.
Thank's.

**Comment by bhadaway** [comment]
Sounds good. I can re-open at that time if there's still an issue.
