### ISSUE TITLE
Allow Requests

### ISSUE THREAD

**Issue by RALLInspired** [bhadaway/stop-spammers#89]
To Whom This May Concern,

We have been using this plugin for sometime now and works great and sometimes too great, lol. I have a question, is there a way to auto send out an email to the person letting them know they have been added to Allow List? If there is it would be great to have, that way I dont have to send out 5-10 emails a week, lol.

Thank you,
RALLInspired.

**Comment by bhadaway** [comment]
There is not. Beyond the can of worms a feature like this would open, the goal is to simplify the plugin, so this feature is not something that will be considered. Sorry.
