### ISSUE TITLE
Preventing admin login notification.

### ISSUE THREAD

**Issue by jasonbassford** [bhadaway/stop-spammers#9]
I feel silly asking this, as it seems somebody else would have already—but I wasn't able to locate the information, either on various support forums or in the interface itself.

How can I stop getting a notification email every time I login to my site's dashboard (as an administrator)? Actually, I know the code I would need to comment out but I'm more interested in the "correct" way of doing this rather than hacking the code...

**Comment by bhadaway** [comment]
From your WP admin main menu, go to:

_Stop Spammers_ > _Challenge & Deny_ > _Notify Webmaster When a User Requests to be Added to the Allow List_ > _Uncheck that box_ > _Save_

If that's not it, can you please share exactly what the wording of the email is and where in the code, in what file, you're seeing that you can comment it out?

Thanks

**Comment by jasonbassford** [comment]
This happens whenever I, as an administrator, login to the dashboard. The exact wording of the email I receive is: 

Stop Spammers Message - An admin logged into your WordPress website [website] on [date] from IP: [IP].

I believe the file with the code responsible is _includes/kpg_ss_notify_admin.php_.  The function, _kpg_ss_notify_admin_action($user_login, $user)_, quite literally doesn't do anything other than send a notification email when an administrator logs in.

The notification seems to have nothing to do with whether or not my own computer's IP is on the allow list. The comment in the code is "// notify admin when the someone logs in.", and the only conditional it checks is (effectively—I'm reversing the logic)  "if (current_user_can('manage_options'))".

**Comment by bhadaway** [comment]
Ah, you're on an out-dated version of Stop Spammers, I'm guessing 6.15? Make sure you upgrade to the latest version.

**Comment by jasonbassford** [comment]
No, I'm on 7.0. I installed it only a couple of weeks ago. I will try removing it and reinstalling it...

**Comment by bhadaway** [comment]
Yes, try a fresh install. But, I'll also push a small update to make sure everyone updating is on the very latest version as well. I've been continually refining a stable 7.0, but it's time to push forward.

**Comment by bhadaway** [comment]
Fixed.
