### ISSUE TITLE
Block from account

### ISSUE THREAD

**Issue by DamnDramaQueen** [bhadaway/stop-spammers#92]
Hi Stop,

Besides typing in the IP address for blocking from the block list, etc

Is there’ a way to hook a block/unblock button directly to the user's account (Username/profile)? The admin can just click to block’em right on their account. This way is more precise as well

Please advise help,
Thanks

**Comment by bhadaway** [comment]
On paper, that might sound like a good idea, but in actuality:

1. It's important that you delete spam users as soon as you discover them.

2. It's important to keep refining your blocking techniques until you weed out most or all spam registrations from getting through in the first place.

If you don't actually delete the accounts, your site will eventually be overrun by dead accounts, and it'll get increasingly harder to organize, view, help, and maintain legitimate users.

In terms of blocking, you can block more than just IPs; you can block usernames, keywords, TLDs, etc.

**Comment by DamnDramaQueen** [comment]
Hi Stop,

You are correct your way to delete and eliminate spams is a good way.  

Does the plugin have this feature ? I looked everywhere for the spam menu/area where I can delete spams. Can you show me where's locate? 

Also, for deleting, those spammers (Users), same thing, where to locate from the plugin?

Please advise help for location,
Thanks

**Comment by bhadaway** [comment]
This is a native WordPress function. Simply go to your Users list in your admin:

https://example.com/wp-admin/users.php

And audit your users.

Managing a website that allows user registration, means this is something you'll have to incorporate into your workflow, even if you weren't using Stop Spammers.

Most spam users are easy to detect and delete. You'll get better at spotting them. If you have hundreds or thousands of spam users, you might have to take a more aggressive approach:

https://www.google.com/search?q=wordpress+delete+ghost+accounts

Every site is different, and you'll come up with your own techniques along the way.

Happy Hunting!
