### ISSUE TITLE
What does it mean “No Accept Header;”

### ISSUE THREAD

**Issue by theturtle626** [bhadaway/stop-spammers#93]
I found some hacker activity in the Log Report : Script => /-/-/-/-/-/-/-/-/-/-/, Reason : No Accept Header;

I set a firewall rule in my firewall to block if someone visits my web site with uri /-/-/-/-/-/-/-/-/-/-/, but nothing blocked, I tested by myself to visit my web site with url http://mysite/-/-/-/-/-/-/-/-/-/-/, the request is blocked by my firewall.

so I wonder the script /-/-/-/-/-/-/-/-/-/-/ reported by Stop Spammers plugin is not exactly what it looks like. Is there a log in some directory to record the full information ? or Can the plugin to record more detailed info about this uri information ? I need it to setup a rule in my firewall, thanks.

**Comment by bhadaway** [comment]
It sounds like the spammer is spoofing the referrer header to get around your rules, which is pretty simple to do.

https://en.wikipedia.org/wiki/Referer_spoofing
https://security.stackexchange.com/questions/66165/does-referrer-header-checking-offer-any-real-world-security-improvement

I would focus more on blocking IP ranges and other patterns you discover related to this spammer.
