### ISSUE TITLE
Not blocking IPs in the Block List

### ISSUE THREAD

**Issue by SleeplessinDC** [bhadaway/stop-spammers#94]
For several IPs I started to add to the Block List recently, I discovered that they were already in the list. The plugin has been working great but lately it isn't blocking IPs that are listed to be blocked.

**Comment by bhadaway** [comment]
In this context, what exactly do you mean by blocking? Do you mean?...

1. Blocking them from registering or leaving comments.

2. Blocking them from even attempting to try those things in the first place, which will still have them showing up in your logs.

If #2, you might add this plugin as well:

https://wordpress.org/plugins/wp-fail2ban/
