### ISSUE TITLE
TLD block list fails sometimes

### ISSUE THREAD

**Issue by JorritHimself** [bhadaway/stop-spammers#97]
This is a difficult issue to replicate or troubleshoot, I guess.
I have added several spammy TLDs to the block list.
I have seen plenty f successful denials of registration based on that list of TLDs.
It includes 'egogap.com', but jut now I had a passed registration of someone@data.egogap.com

**Comment by bhadaway** [comment]
You can only block TLDs (which are the .com part), but not entire domains in this section.

For example, a list of blocked TLDs would look like this:

```
.ar
.cn
.gq
.nl
.pl
.pw
.ru
.tk
.xyz
.xxx
.club
.at
.eu
.asia
```

You should try adding _egogap_ to the spam words block list.
