### ISSUE TITLE
Disable email notice

### ISSUE THREAD

**Issue by BorisKamp** [bhadaway/stop-spammers#98]
Hi guys, 

I keep getting emails like:

-----------------------------------------
Webmaster,

A request has been received from someone who has been marked as a spammer by the Stop Spammers plugin.

You are being notified because you have checked off the box on the settings page indicating that you wanted this email.

The information from the request is:

Time: 2019/06/04 07:25:06

User IP: 31.184.238.111

User Email: fghserf@bigmir.net

Spam Reason:

User Message: Your style is really unique compared to other folks I have read stuff from. Many thanks for posting when you\'ve got the opportunity, Guess I will just bookmark this page.

Please be aware that the user has been recognized as a potential spammer.

Some spam bots fill out the request form with a fake explanation.

— Stop Spammers
-----------------------------------------

from the plugin, it mentions a checkbox, but I cannot find it anywhere. Where is this located so I can disable it.

**Comment by bhadaway** [comment]
_Stop Spammers > Challenge & Deny > Notify Webmaster When a User Requests to be Added to the Allow List_
