### ISSUE TITLE
Blocked User Message

### ISSUE THREAD

**Issue by buzzinbilly** [bhadaway/stop-spammers#99]
Hi,

Im getting the message in the attached screenshot appear for new users trying to register to my woocommerce site.

Is this a security measure from your plugin or caused elsewhere ? 

Regards
Billy
![IMG-20190624-WA0005](https://user-images.githubusercontent.com/52166240/60024471-b7398280-968f-11e9-8696-858b62e56f3a.jpg)

**Comment by bhadaway** [comment]
Yes, please see the FAQs concerning WooCommerce:

https://github.com/bhadaway/stop-spammers/wiki/FAQs

Thanks

**Comment by buzzinbilly** [comment]
Thanks
